// Schools data
const schoolsData = [
  {
    id: 1,
    name: "SMKN 1 PACET",
    location: "Cianjur, Jawa Barat",
    modules: ["Usaha Perjalanan Wisata (UPW)"],
    competencies: ["D2.TRA.CL2.15 Produce travel documentation on a computer"],
  },
  {
    id: 2,
    name: "SMK PGRI SUBANG",
    location: "Subang, Jawa Barat",
    modules: [
      "Food & beverage",
      "Front office",
      "Food Production",
      "Tour Guiding",
      "UPW",
    ],
    competencies: [
      "D1.HBS.CLS.01",
      "D1.HBS.CLS.02",
      "D1.HBS.CLS.10",
      "D1.HBS.CLS.12",
      "D1.HBS.CLS.16",
      "D1.HGE.CL7.13",
      "D1.HGA.CL6.02",
    ],
  },
  {
    id: 3,
    name: "SMKN 1 BANDUNG",
    location: "Bandung, Jawa Barat",
    modules: ["Food & beverage", "Front office", "Food Production"],
    competencies: [
      "D1.HBS.CLS.01",
      "D1.HBS.CLS.02",
      "D1.HBS.CLS.10",
      "D1.HBS.CLS.12",
      "D1.HBS.CLS.16",
      "D1.HGE.CL7.13",
      "D1.HGA.CL6.02",
    ],
  },
  {
    id: 4,
    name: "SMKN 3 BANDUNG",
    location: "Bandung, Jawa Barat",
    modules: ["Food & beverage", "Front office", "Food Production"],
    competencies: [
      "D1.HBS.CLS.01",
      "D1.HBS.CLS.02",
      "D1.HBS.CLS.10",
      "D1.HBS.CLS.12",
      "D1.HBS.CLS.16",
      "D1.HGE.CL7.13",
      "D1.HGA.CL6.02",
    ],
  },
  {
    id: 5,
    name: "SMKN 9 BANDUNG",
    location: "Bandung, Jawa Barat",
    modules: ["Perhotelan & Jasa Pariwisata"],
    competencies: ["D1.HRS.CL08", "D1.HOT.CL1.08"],
  },
  {
    id: 6,
    name: "SMKN 1 BOGOR",
    location: "Bogor, Jawa Barat",
    modules: ["Food & beverage", "Front office", "Food Production"],
    competencies: [
      "D1.HBS.CLS.01",
      "D1.HBS.CLS.02",
      "D1.HBS.CLS.10",
      "D1.HBS.CLS.12",
      "D1.HBS.CLS.16",
      "D1.HGE.CL7.13",
      "D1.HGA.CL6.02",
    ],
  },
  {
    id: 7,
    name: "SMKN 3 BOGOR",
    location: "Bogor, Jawa Barat",
    modules: ["Food & beverage", "Front office", "Food Production"],
    competencies: [
      "D1.HBS.CLS.01",
      "D1.HBS.CLS.02",
      "D1.HBS.CLS.10",
      "D1.HBS.CLS.12",
      "D1.HBS.CLS.16",
      "D1.HGE.CL7.13",
      "D1.HGA.CL6.02",
    ],
  },
  {
    id: 8,
    name: "SMK ALWAFA CIWIDEY",
    location: "Bandung, Jawa Barat",
    modules: ["Usaha Layanan Pariwisata"],
    competencies: ["D2.TRM.CL9.03"],
  },
  {
    id: 9,
    name: "SMKN 1 CIAMIS",
    location: "Ciamis, Jawa Barat",
    modules: ["Food & beverage", "Front office", "Food Production"],
    competencies: [
      "D1.HBS.CLS.01",
      "D1.HBS.CLS.02",
      "D1.HBS.CLS.10",
      "D1.HBS.CLS.12",
      "D1.HBS.CLS.16",
      "D1.HGE.CL7.13",
      "D1.HGA.CL6.02",
    ],
  },
  {
    id: 10,
    name: "SMK METLAND",
    location: "Jakarta",
    modules: [
      "Food & beverage",
      "Front office",
      "Food Production",
      "Sales",
      "Kitchen Knowledge",
      "Bar",
      "Housekeeping",
      "Laundry",
    ],
    competencies: [
      "D1.HBS.CLS.01",
      "D1.HBS.CLS.02",
      "D1.HBS.CLS.10",
      "D1.HBS.CLS.12",
      "D1.HBS.CLS.16",
      "D1.HGE.CL7.13",
      "D1.HGA.CL6.02",
    ],
  },
  {
    id: 11,
    name: "SMKN 57 JAKARTA",
    location: "Jakarta",
    modules: ["Food & beverage", "Front office", "Food Production"],
    competencies: [
      "D1.HBS.CLS.01",
      "D1.HBS.CLS.02",
      "D1.HBS.CLS.10",
      "D1.HBS.CLS.12",
      "D1.HBS.CLS.16",
      "D1.HGE.CL7.13",
      "D1.HGA.CL6.02",
    ],
  },
  {
    id: 12,
    name: "SMKN 3 MALANG",
    location: "Malang, Jawa Timur",
    modules: ["Tour Operation"],
    competencies: [
      "D2.TRM.CL9.03",
      "D1.HSM.CL5.06",
      "D2.TRM.CL9.02",
      "D1.HML.CL10.05",
      "D1.HML.CL10.09",
      "D1.HML.CL10.14",
      "D2.TRM.CL9.07",
      "D1.HGE.CL7.09",
      "D2.TGA.CL6.09",
    ],
  },
  {
    id: 13,
    name: "SMKN 2 BATAM",
    location: "Batam, Kepulauan Riau",
    modules: ["Perhotelan dan Tata Boga"],
    competencies: ["D1.HRS.CL1.08", "D1.HFI.CL8.08", "D2.THO.CL4.18"],
  },
  {
    id: 14,
    name: "SMKN 3 PEMATANG SIANTAR",
    location: "Pematang Siantar, Sumatera Utara",
    modules: ["Food & beverage", "Front office", "Food Production"],
    competencies: [
      "D1.HBS.CLS.01",
      "D1.HBS.CLS.02",
      "D1.HBS.CLS.10",
      "D1.HBS.CLS.12",
      "D1.HBS.CLS.16",
      "D1.HGE.CL7.13",
      "D1.HGA.CL6.02",
    ],
  },
  {
    id: 15,
    name: "SMKN 3 PANGKAL PINANG",
    location: "Pangkal Pinang, Bangka Belitung",
    modules: ["Food & beverage", "Front office", "Food Production"],
    competencies: [
      "D1.HBS.CLS.01",
      "D1.HBS.CLS.02",
      "D1.HBS.CLS.10",
      "D1.HBS.CLS.12",
      "D1.HBS.CLS.16",
      "D1.HGE.CL7.13",
      "D1.HGA.CL6.02",
    ],
  },
  {
    id: 16,
    name: "SMKN 6 PALEMBANG",
    location: "Palembang, Sumatera Selatan",
    modules: ["Food & beverage", "Front office", "Food Production"],
    competencies: [
      "D1.HBS.CLS.01",
      "D1.HBS.CLS.02",
      "D1.HBS.CLS.10",
      "D1.HBS.CLS.12",
      "D1.HBS.CLS.16",
      "D1.HGE.CL7.13",
      "D1.HGA.CL6.02",
    ],
  },
  {
    id: 17,
    name: "SMKN 2 MATARAM",
    location: "Mataram, Nusa Tenggara Barat",
    modules: ["Provide Arrival and Departure Assistance"],
    competencies: ["D2.TTG.CL3.17"],
  },
  {
    id: 18,
    name: "SMKN 27 JAKARTA",
    location: "Jakarta",
    modules: ["Food & beverage", "Front office", "Food Production"],
    competencies: [
      "D1.HBS.CLS.10",
      "D1.HBS.CLS.12",
      "D1.HBS.CLS.16",
      "D1.HGE.CL7.13",
      "D1.HGA.CL6.02",
    ],
  },
  {
    id: 19,
    name: "SMKN 1 PANDEGLANG",
    location: "Pandeglang, Banten",
    modules: ["Food & beverage", "Front office", "Food Production"],
    competencies: [
      "D1.HBS.CLS.01",
      "D1.HBS.CLS.02",
      "D1.HBS.CLS.10",
      "D1.HBS.CLS.12",
      "D1.HBS.CLS.16",
      "D1.HGE.CL7.13",
      "D1.HGA.CL6.02",
    ],
  },
];
